`define STATE_CPU_WRITE_WAIT 2'b0
`define STATE_CPU_TO_UART_WRITE 2'b1

`define STATE_BEGIN_WRITE 2'b10
`define STATE_WAITING_WRITE 2'b00
`define STATE_STOP_WRITE 2'b01

`define STATE_BEGIN_READ 2'b10
`define STATE_WAITING_READ 2'b00
`define STATE_STOP_READ 2'b01